### ISSUE TITLE
Missing diff_gaussian_rasterization_fea folder in the repository

### ISSUE THREAD

**Issue by Mrashe** [USTC3DV/PortraitGen-code#4]
Hello,

I followed the instructions in the README and tried to run the code. However, the command `cd diff_gaussian_rasterization_fea` is mentioned, but the corresponding folder does not exist in the repository. Could you please clarify if this folder has been moved, renamed, or if it is missing?

Thank you for your help!

**Comment by XuanGhahahaha** [comment]
Hi 

Thank you for your interest in our work!

I have uploaded the diff_gaussian_rasterization_fea module. You could clone the repository and try again!
