### ISSUE TITLE
Can't find two smplx files: SMPLX_NEUTRAL_bc.npz and wflw_to_pts51.txt.

### ISSUE THREAD

**Issue by JackEasson** [USTC3DV/PortraitGen-code#6]
Hi, thank you so much for your work!
I've failed to find the two files about SMPLX in provided URL. Could you please give me some detail urls for them?
Thanks a lot.
![lost](https://github.com/user-attachments/assets/15bf7454-bebb-4dae-bc8e-cca1b607d007)

**Comment by XuanGhahahaha** [comment]
Hi, thank you for your interest in our work!

These 2 files are not needed any more, I forget to delete them in README requirements. You could just ignore them and have a try!

Feel free to tell me if you meet any other issues.
