### ISSUE TITLE
Couldn't Find SMPLX_to_J14.pkl

### ISSUE THREAD

**Issue by xyhanHIT** [USTC3DV/PortraitGen-code#8]
Hi, thank you so much for your work! I couldn't find "SMPLX_to_J14.pkl" in provided URL. Could you please give me some detail urls for it? Thanks a lot!

**Comment by XuanGhahahaha** [comment]
Hi,

Thank you for your interest in our work!

You could download it at https://huggingface.co/camenduru/SMPLer-X/blob/main/SMPLX_to_J14.pkl

Feel free to tell me if you meet any other issues in this repo.
