### ISSUE TITLE
vals = self.model.encode(img, batch={},training=False) TypeError: encode() got multiple values for argument 'batch'

### ISSUE THREAD

**Issue by njust-yang** [USTC3DV/PortraitGen-code#9]
gaussian_training/emoca_recog.py  how to resolve it ?

**Comment by XuanGhahahaha** [comment]
Hi, thank you for your interest in our work!

I didn't meet this problem when running my experiments. Maybe you could go to EMOCA repo to ask this question.

Alternatively, you could delete the lines related to EMOCA similarity loss directly. Our method could still get a reasonable result without EMOCA loss.

**Comment by njust-yang** [comment]
I have addressed this problem，thanks！

---- Replied Message ----
| From | ***@***.***> |
| Date | 12/22/2024 15:03 |
| To | USTC3DV/PortraitGen-code ***@***.***> |
| Cc | Jay ***@***.***>,
Author ***@***.***> |
| Subject | Re: [USTC3DV/PortraitGen-code] vals = self.model.encode(img, batch={},training=False) TypeError: encode() got multiple values for argument 'batch' (Issue #9) |

Hi, thank you for your interest in our work!

I didn't meet this problem when running my experiments. Maybe you could go to EMOCA repo to ask this question.

Alternatively, you could delete the lines related to EMOCA similarity loss directly. Our method could still get a reasonable result without EMOCA loss.

**Comment by lishaoxu1994** [comment]
> I have addressed this problem，thanks！
> […](#)

I have encountered the same problem. Can you share how you solved it?

**Comment by Anonymous2067** [comment]
Delete the lines related to EMOCA similarity loss directly

**Comment by lishaoxu1994** [comment]
> Delete the lines related to EMOCA similarity loss directly

Thanks for sharing, I modified the code to 

vals = self.model.encode(batch={'image':img}, training=False)

This seems to work.
